FROM golang:1.25.8-alpine3.23 AS builder

RUN apk update && apk add --no-cache git curl

RUN go install github.com/air-verse/air@latest

WORKDIR /app



COPY . .

CMD ["air", "--config", ".air.worker.toml"]