

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS users (
	user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
	user_email VARCHAR(150) NOT NULL UNIQUE,
	user_password VARCHAR(90) NOT NULL,
	user_fullname VARCHAR(150) NOT NULL,
	user_age INT CHECK (user_age >= 1 AND user_age <= 100) NOT NULL,
	user_status INT CHECK (user_status IN (1, 2,3)) NOT NULL DEFAULT 1,
	user_level INT CHECK (user_level IN (1, 2,3)) NOT NULL DEFAULT 1,
	user_updated_at TIMESTAMPZ  NOT NULL DEFAULT NOW(),
	user_created_at TIMESTAMPZ  NOT NULL DEFAULT NOW(),
	user_deleted_at TIMESTAMPZ DEFAULT NULL,

);


COMMENT ON COLUMN users.user_age IS 'Age must be between 1 and 100';
COMMENT ON COLUMN users.user_status IS '1: Active, 2: Inactive, 3: Pending';
COMMENT ON COLUMN users.user_level IS '1: Admin, 2: Moderator, 3: Member';


CREATE INDEX IF NOT EXISTS idx_users_level ON users (user_level);
CREATE INDEX IF NOT EXISTS idx_users_status ON users (user_status);
CREATE INDEX IF NOT EXISTS idx_users_created_at ON users (user_created_at);
CREATE INDEX IF NOT EXISTS idx_users_deleted_at ON users (user_deleted_at);

CREATE OR REPLACE FUNCTION update_user_updated_at()
RETURNS TRIGGER AS $$
BEGIN
	NEW.user_updated_at = NOW();
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION update_user_updated_at();